const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILED = 'LOGIN_FAILED';

const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
const SIGNUP_FAILED = 'SIGNUP_FAILED';

const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
const LOGOUT_FAILED = 'LOGOUT_FAILED';

const FETCH_AUTH_REQUEST = 'FETCH_AUTH_REQUEST';
const FETCH_AUTH_SUCCESS = 'FETCH_AUTH_SUCCESS';
const FETCH_AUTH_FAILED = 'FETCH_AUTH_FAILED';

const TASKS_FETCH_REQUEST = 'TASKS_FETCH_REQUEST';
const TASKS_FETCH_SUCCESS = 'TASKS_FETCH_SUCCESS';
const TASKS_FETCH_FAILED = 'TASKS_FETCH_FAILED';

const TASK_ADD_REQUEST = 'TASK_ADD_REQUEST';
const TASK_ADD_SUCCESS = 'TASK_ADD_SUCCESS';
const TASK_ADD_FAILED = 'TASK_ADD_FAILED';

const TASK_EDIT_REQUEST = 'TASK_EDIT_REQUEST';
const TASK_EDIT_SUCCESS = 'TASK_EDIT_SUCCESS';
const TASK_EDIT_FAILED = 'TASK_EDIT_FAILED';

const TASK_DELETE_REQUEST = 'TASK_DELETE_REQUEST';
const TASK_DELETE_SUCCESS = 'TASK_DELETE_SUCCESS';
const TASK_DELETE_FAILED = 'TASK_DELETE_FAILED';

export {
    LOGIN_REQUEST,
    LOGIN_FAILED,
    LOGIN_SUCCESS,
    SIGNUP_REQUEST,
    SIGNUP_FAILED,
    SIGNUP_SUCCESS,
    LOGOUT_REQUEST,
    LOGOUT_FAILED,
    LOGOUT_SUCCESS,
    FETCH_AUTH_REQUEST,
    FETCH_AUTH_SUCCESS,
    FETCH_AUTH_FAILED,
    TASKS_FETCH_REQUEST,
    TASKS_FETCH_SUCCESS,
    TASKS_FETCH_FAILED,
    TASK_ADD_REQUEST,
    TASK_ADD_SUCCESS,
    TASK_ADD_FAILED,
    TASK_EDIT_REQUEST,
    TASK_EDIT_SUCCESS,
    TASK_EDIT_FAILED,
    TASK_DELETE_REQUEST,
    TASK_DELETE_SUCCESS,
    TASK_DELETE_FAILED,
}